---
packages:
  shelly25: !include common/shelly25-light-light.yaml
substitutions:
  device_name: moo-shelly25-13
  light_1: Bedroom Downlight 01
  light_2: Bedroom Downlight 02
  sensor_1: Bedroom Switch 01
  sensor_2: Bedroom Switch 02
