substitutions:
  device_name: moo-hlw8012-02
  switch_1: Dryer

packages:
  downlight: !include common/hlw8012.yaml

text_sensor:
  - platform: template
    name: ${switch_1} Mode
    id: mode

interval:
  - interval: 1000ms
    then:
      - if:
          condition:
            for:
              time: 10s
              condition:
                sensor.in_range:
                  id: power
                  below: 50
          then:
            - text_sensor.template.publish:
                id: mode
                state: Idle
      - if:
          condition:
            for:
              time: 10s
              condition:
                sensor.in_range:
                  id: power
                  above: 50
                  below: 250
          then:
            - text_sensor.template.publish:
                id: mode
                state: Airing
      - if:
          condition:
            for:
              time: 10s
              condition:
                sensor.in_range:
                  id: power
                  above: 250
                  below: 1000.0
          then:
            - text_sensor.template.publish:
                id: mode
                state: Low
      - if:
          condition:
            for:
              time: 10s
              condition:
                sensor.in_range:
                  id: power
                  above: 1000.0
          then:
            - text_sensor.template.publish:
                id: mode
                state: Regular