---
packages:
  shelly25: !include common/shelly25-light-light.yaml
substitutions:
  device_name: moo-shelly25-07
  light_1: Office Downlight 03
  light_2: Office Downlight 04
  sensor_1: Office Switch 03
  sensor_2: Office Switch 04
