substitutions:
  device_name: moo-shelly25-03
  sensor_1: Stairwell Light Switch
  sensor_2: Downstairs Landing Light Switch
  light_1: Stairwell Light
  light_2: Downstairs Landing Light

packages:
  shelly25: !include common/shelly25-light.yaml