---
packages:
  shelly25: !include common/shelly25-light-light.yaml
substitutions:
  device_name: moo-shelly25-02
  light_1: Driveway Downlight 01
  light_2: Entrance Downlight 01
  sensor_1: Entrance Switch 01
  sensor_2: Entrance Switch 02
