---
packages:
  shelly25: !include common/shelly25-light-light.yaml
substitutions:
  device_name: moo-shelly25-03
  light_1: Stairwell Nightlight 01
  light_2: Stairwell Downlight 02
  sensor_1: Stairwell Switch 02
  sensor_2: Stairwell Switch 03
