---
binary_sensor:
- entity_category: diagnostic
  name: ${device_name} Status
  platform: status
captive_portal:
esphome:
  board: ${device_board}
  name: ${device_name}
  platform: ${device_platform}
  project:
    name: illallangi.moonya
    version: 1.0.0
interval:
- interval: 1s
  then:
  - if:
      condition:
        for:
          condition:
            not:
              text_sensor.state:
                id: lwt_sensor
                state: online
          time: 60s
      then:
      - switch.turn_on: restart_switch
logger:
  baud_rate: 0
  level: NONE
mdns:
mqtt:
  broker: hass.illallangi.enterprises
  discovery: true
  topic_prefix: esphome/${device_name}
ota:
sensor:
- id: uptime_sensor
  name: ${device_name} Device Uptime
  platform: uptime
  update_interval: 60s
- id: wifi_sensor
  name: ${device_name} WiFi Signal
  platform: wifi_signal
  update_interval: 60s
switch:
- id: restart_switch
  name: ${device_name} Restart
  platform: restart
text_sensor:
- bssid:
    name: ${device_name} BSSID
  ip_address:
    name: ${device_name} IP Address
  mac_address:
    name: ${device_name} MAC Address
  platform: wifi_info
  ssid:
    name: ${device_name} SSID
- id: version_sensor
  name: ${device_name} Firmware Version
  platform: version
- entity_category: diagnostic
  id: lwt_sensor
  name: ${device_name} MQTT Connection Status
  platform: mqtt_subscribe
  topic: esphome/${device_name}/status
web_server:
wifi:
  ap:
    password: 0407384998
    ssid: ${device_name}
  networks:
  - password: 0407384998
    ssid: moonya
