---
binary_sensor:
- entity_category: diagnostic
  name: ${device_name} Status
  platform: status
captive_portal:
esphome:
  board: ${device_board}
  name: ${device_name}
  platform: ${device_platform}
  project:
    name: illallangi.moonya
    version: 1.0.0
mqtt:
  broker: hass.illallangi.enterprises
  discovery: true
  topic_prefix: esphome/${device_name}
sensor:
- id: uptime_sensor
  name: ${device_name} Device Uptime
  platform: uptime
  update_interval: 60s
- id: wifi_sensor
  name: ${device_name} WiFi Signal
  platform: wifi_signal
  update_interval: 60s
switch:
- id: restart_switch
  name: ${device_name} Restart
  platform: restart
text_sensor:
- bssid:
    name: ${device_name} BSSID
  ip_address:
    name: ${device_name} IP Address
  mac_address:
    name: ${device_name} MAC Address
  platform: wifi_info
  ssid:
    name: ${device_name} SSID
- id: version_sensor
  name: ${device_name} Firmware Version
  platform: version
web_server:
wifi:
  ap:
    password: 0407384998
    ssid: ${device_name}
  domain: .alfa.illallangi.enterprises
  networks:
  - password: 0407384998
    ssid: moo-iot
  reboot_timeout: 1min
