# DT-Light ESP8285 Lighting Module (DMP-L1)
# https://templates.blakadder.com/DMP-L1.html

packages:
  device_base: !include esp8285.yaml


# GPIO4 - W
# GPIO5 - B
# GPIO12 - R
# GPIO13 - Y
# GPIO14 - G

output:
- platform: esp8266_pwm
  pin: GPIO4
  id: output_r
- platform: esp8266_pwm
  pin: GPIO13
  id: output_g
- platform: esp8266_pwm
  pin: GPIO5
  id: output_b
- platform: esp8266_pwm
  pin: GPIO12
  id: output_cw
- platform: esp8266_pwm
  pin: GPIO14
  id: output_ww

light:
- name: ${light_1}
  id: light_1
  platform: rgbww
  color_interlock: true
  red: output_r
  green: output_g
  blue: output_b
  warm_white: output_ww
  cold_white: output_cw
  cold_white_color_temperature: 5700 K
  warm_white_color_temperature: 3000 K
  restore_mode: RESTORE_DEFAULT_OFF
  effects:
  - pulse: {}
  - pulse:
      name: Fast Pulse
      transition_length: 0.5s
      update_interval: 0.5s
  - pulse:
      name: Slow Pulse
      # transition_length: 1s      # defaults to 1s
      update_interval: 2s
  - random: {}
  - random:
      name: Fast Random
      transition_length: 0s
      update_interval: 1s
  - strobe: {}
  - strobe:
      colors:
      - blue: 0%
        brightness: 100%
        duration: 500ms
        green: 90%
        red: 100%
        state: true
      - duration: 250ms
        state: false
      - blue: 0%
        brightness: 100%
        duration: 500ms
        green: 100%
        red: 0%
        state: true
      name: Strobe Effect With Custom Values
  - flicker: {}
  - flicker:
      alpha: 95%
      intensity: 1.5%
      name: Flicker Effect With Custom Values
  - lambda:
      lambda: |-
        static int state = rand() % 12;
        auto call = id(light_1).turn_on();
        call.set_transition_length(1000);
        if (state == 0) {
          call.set_rgb(1.0, 0.0, 0.0);
        } else if (state == 1) {
          call.set_rgb(1.0, 0.5, 0.0);
        } else if (state == 2) {
          call.set_rgb(1.0, 1.0, 0.0);
        } else if (state == 3) {
          call.set_rgb(0.5, 1.0, 0.0);
        } else if (state == 4) {
          call.set_rgb(0.0, 1.0, 0.0);
        } else if (state == 5) {
          call.set_rgb(0.0, 1.0, 0.5);
        } else if (state == 6) {
          call.set_rgb(0.0, 1.0, 1.0);
        } else if (state == 7) {
          call.set_rgb(0.0, 0.5, 1.0);
        } else if (state == 8) {
          call.set_rgb(0.0, 0.0, 1.0);
        } else if (state == 9) {
          call.set_rgb(0.5, 0.0, 1.0);
        } else if (state == 10) {
          call.set_rgb(1.0, 0.0, 1.0);
        } else if (state == 11) {
          call.set_rgb(1.0, 0.0, 0.5);
        }
        call.perform();
        state++;
        if (state == 12)
          state = 0;
      name: Rainbow
      update_interval: 1s
