---
# https://www.esphome-devices.com/devices/Shelly-1
binary_sensor:
- id: sensor_1
  name: ${sensor_1}
  pin:
    number: GPIO5
  platform: gpio
light:
- id: light_1
  name: ${light_1}
  output: output_1
  platform: binary
  restore_mode: RESTORE_DEFAULT_OFF
output:
- id: output_1
  pin:
    number: GPIO4
  platform: gpio
packages:
  device_base: !include esp01_1m.yaml
